/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2018-01-11 08:40:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.scripts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class event_js_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/quzhinan/Documents/workspace/ienursing-prod-server/webapp/WEB-INF/lib/struts2-core-2.3.32.jar!/META-INF/struts-tags.tld", Long.valueOf(1488773180000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.32.jar", Long.valueOf(1515659608000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/javascript; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function evt_open_editor_week(eventId, itemType, callbackSuccess, callbackFailed, callbackClose, defval) {\n");
      out.write("\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tvar box = j$(\"#evt_editor_box\");\n");
      out.write("\tif (box.length == 0) {\n");
      out.write("\t\tbox = j$(\"<div id='evt_editor_box' title='イベント編集'></div>\");\n");
      out.write("\t\tbox.appendTo(j$(document.body));\n");
      out.write("\t\tbox.dialog({\n");
      out.write("\t\t\tautoOpen: false,\n");
      out.write("\t\t\tresizable: false,\n");
      out.write("\t\t\tmodal: true,\n");
      out.write("\t\t\twidth: 700,\n");
      out.write("\t\t\theight: 580,\n");
      out.write("\t\t\tclose: function(event, ui) {\n");
      out.write("\t\t\t\tif (callbackClose != undefined) {\n");
      out.write("\t\t\t\t\tcallbackClose();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t} else {\n");
      out.write("\t\tbox.html(\"\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar buttons = new Array();\n");
      out.write("\tif (eventId > 0) {\n");
      out.write("\t\tbox.dialog(\"option\", \"title\", \"イベント変更\");\n");
      out.write("\t\tif (itemType == 2) {\t/* schedule */\n");
      out.write("\t\t\tbuttons.push(\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"実績編集\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tevt_modify_item_data(callbackSuccess, callbackFailed, eventId);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"キャンセル扱い\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tif (confirm(\"この訪問サービスをキャンセルしてよろしいですか。\") == true) {\n");
      out.write("\t\t\t\t\t\t\t\tevt_cancel_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\tbuttons.push(\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"削除\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tif (confirm(\"この訪問サービスを削除してよろしいですか。\") == true) {\n");
      out.write("\t\t\t\t\t\t\tevt_delete_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t\tif (itemType == 2) {\t/* schedule */\n");
      out.write("\t\t\tbuttons.push(\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"コピー\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tevt_copy_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t);\n");
      out.write("\t\t}\n");
      out.write("\t\tbuttons.push(\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"保存\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tevt_save_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"閉じる\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tj$(this).dialog(\"close\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t} else {\n");
      out.write("\t\tbox.dialog(\"option\", \"title\", \"イベント新規\");\n");
      out.write("\t\tbuttons.push(\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"登録\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tevt_save_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"閉じる\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tj$(this).dialog(\"close\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t}\n");
      out.write("\tbox.dialog(\"option\", \"buttons\", buttons);\n");
      out.write("\tbox.dialog({\n");
      out.write("  \t\topen: function( event, ui ) {\n");
      out.write("\t\t\tj$(\"[name=serviceCode]\").focus();\n");
      out.write("\t\t\tj$(\"[name=serviceDate]\").datepicker({\n");
      out.write("\t\t\t\tdateFormat: \"yymmdd\",\n");
      out.write("\t\t\t\tonClose: function(selectedDate) {\n");
      out.write("\t\t\t\t\tj$(\"[name=timeStartHour]\").focus();\n");
      out.write("\t\t\t\t\tif (eventId == 0) {\n");
      out.write("\t\t\t\t\t\tj$(\"#serviceYm\").val(selectedDate.substring(0, 6));\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("  \t\t}\n");
      out.write("\t});\n");
      out.write("\tbox.load(url, {id: eventId, type: itemType}, function(){\n");
      out.write("\t\tif (eventId == 0 && defval != undefined) {\n");
      out.write("\t\t\tfor (var key in defval) {\n");
      out.write("\t\t\t\tbox.find(\"[name='\" + key  + \"']\").val(defval[key]);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tbox.dialog(\"open\");\n");
      out.write("\t\t\n");
      out.write("\t\tvar buttonset = box.parent().find(\".ui-dialog-buttonset\");\n");
      out.write("\t\tif (buttonset.find(\"button\").length > 3) {\n");
      out.write("\t\t\tvar buttons = new Array();\n");
      out.write("\t\t\tbuttons[0] = buttonset.find(\"button\")[0];\n");
      out.write("\t\t\tbuttons[1] = buttonset.find(\"button\")[1];\n");
      out.write("\t\t\tfor (var i=0; i<buttons.length; i++) {\n");
      out.write("\t\t\t\tj$(buttons[i]).find(\"span\").css(\"background-color\", \"#f5f435\");\n");
      out.write("\t\t\t\tj$(buttons[i]).find(\"span\").css(\"border-radius\", \"5px\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tj$(buttons[buttons.length-1]).css(\"margin-right\", \"30px\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_open_editor(isCancel, eventId, itemType, callbackSuccess, callbackFailed, callbackClose, defval) {\n");
      out.write("\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f1(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tvar box = j$(\"#evt_editor_box\");\n");
      out.write("\tif (box.length == 0) {\n");
      out.write("\t\tbox = j$(\"<div id='evt_editor_box' title='イベント編集'></div>\");\n");
      out.write("\t\tbox.appendTo(j$(document.body));\n");
      out.write("\t\tbox.dialog({\n");
      out.write("\t\t\tautoOpen: false,\n");
      out.write("\t\t\tresizable: false,\n");
      out.write("\t\t\tmodal: true,\n");
      out.write("\t\t\twidth: 700,\n");
      out.write("\t\t\theight: 620,\n");
      out.write("\t\t\tclose: function(event, ui) {\n");
      out.write("\t\t\t\tif (callbackClose != undefined) {\n");
      out.write("\t\t\t\t\tcallbackClose();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t} else {\n");
      out.write("\t\tbox.html(\"\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar buttons = new Array();\n");
      out.write("\tif (eventId > 0) {\n");
      out.write("\t\tbox.dialog(\"option\", \"title\", \"イベント変更\");\n");
      out.write("\t\tif (itemType == 2) {\t/* schedule */\n");
      out.write("\t\t\tif(isCancel) {\n");
      out.write("\t\t\t\tbuttons.push(\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"実績編集\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tevt_modify_item_data(callbackSuccess, callbackFailed, eventId);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"キャンセル解除\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tif (confirm(\"この訪問サービスをキャンセル解除してよろしいですか。\") == true) {\n");
      out.write("\t\t\t\t\t\t\t\tevt_not_cancel_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tbuttons.push(\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"実績編集\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tevt_modify_item_data(callbackSuccess, callbackFailed, eventId);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"キャンセル扱い\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tif (confirm(\"この訪問サービスをキャンセルしてよろしいですか。\") == true) {\n");
      out.write("\t\t\t\t\t\t\t\tevt_cancel_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tbuttons.push(\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"削除\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tvar isPlus = j$(\"input[name='achievementExist']\").val();\n");
      out.write("\t\t\t\t\t\tvar msg = \"この訪問サービスを削除してよろしいですか。\" + (isPlus == \"true\" ? \"（注意：訪問記録が存在します。）\" : \"\");\n");
      out.write("\t\t\t\t\t\tif (confirm(msg) == true) {\n");
      out.write("\t\t\t\t\t\t\tevt_delete_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t\tif (itemType == 2) {\t/* schedule */\n");
      out.write("\t\t\tbuttons.push(\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ttext: \"コピー\", \n");
      out.write("\t\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\t\tevt_copy_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t);\n");
      out.write("\t\t}\n");
      out.write("\t\tbuttons.push(\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"保存\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tevt_save_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"閉じる\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tj$(this).dialog(\"close\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t} else {\n");
      out.write("\t\tbox.dialog(\"option\", \"title\", \"イベント新規\");\n");
      out.write("\t\tbuttons.push(\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"登録\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tevt_save_item_data(callbackSuccess, callbackFailed);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext: \"閉じる\", \n");
      out.write("\t\t\t\t\tclick: function(){\n");
      out.write("\t\t\t\t\t\tj$(this).dialog(\"close\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t}\n");
      out.write("\tbox.dialog(\"option\", \"buttons\", buttons);\n");
      out.write("\tbox.dialog({\n");
      out.write("  \t\topen: function( event, ui ) {\n");
      out.write("\t\t\tj$(\"[name=serviceCode]\").focus();\n");
      out.write("\t\t\tj$(\"[name=serviceDate]\").datepicker({\n");
      out.write("\t\t\t\tdateFormat: \"yymmdd\",\n");
      out.write("\t\t\t\tonClose: function(selectedDate) {\n");
      out.write("\t\t\t\t\tj$(\"[name=timeStartHour]\").focus();\n");
      out.write("\t\t\t\t\tif (eventId == 0) {\n");
      out.write("\t\t\t\t\t\tj$(\"#serviceYm\").val(selectedDate.substring(0, 6));\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("  \t\t}\n");
      out.write("\t});\n");
      out.write("\tvar customerId;\n");
      out.write("\tif (defval == undefined) {\n");
      out.write("\t\tcustomerId = 0;\n");
      out.write("\t} else {\n");
      out.write("\t\tif (defval['customerId'] != null) {\n");
      out.write("\t\t\tcustomerId = defval['customerId'];\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tcustomerId = -1;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tbox.load(url, {id: eventId, type: itemType, defaultCustomerId: customerId}, function(){\n");
      out.write("\t\tif (eventId == 0 && defval != undefined) {\n");
      out.write("\t\t\tfor (var key in defval) {\n");
      out.write("\t\t\t\tbox.find(\"[name='\" + key  + \"']\").val(defval[key]);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tbox.dialog(\"open\");\n");
      out.write("\t\t\n");
      out.write("\t\tvar buttonset = box.parent().find(\".ui-dialog-buttonset\");\n");
      out.write("\t\tif (buttonset.find(\"button\").length > 3) {\n");
      out.write("\t\t\tvar buttons = new Array();\n");
      out.write("\t\t\tbuttons[0] = buttonset.find(\"button\")[0];\n");
      out.write("\t\t\tbuttons[1] = buttonset.find(\"button\")[1];\n");
      out.write("\t\t\tfor (var i=0; i<buttons.length; i++) {\n");
      out.write("\t\t\t\tj$(buttons[i]).find(\"span\").css(\"background-color\", \"#f5f435\");\n");
      out.write("\t\t\t\tj$(buttons[i]).find(\"span\").css(\"border-radius\", \"5px\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tj$(buttons[buttons.length-1]).css(\"margin-right\", \"30px\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function evt_save_item_data(callbackSuccess, callbackFailed) {\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f2(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tevt_post_item_data(url, callbackSuccess, callbackFailed);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_copy_item_data(callbackSuccess, callbackFailed) {\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f3(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tevt_post_item_data(url, callbackSuccess, callbackFailed);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_delete_item_data(callbackSuccess, callbackFailed) {\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f4(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tevt_post_item_data(url, callbackSuccess, callbackFailed);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_cancel_item_data(callbackSuccess, callbackFailed) {\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f5(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tevt_post_item_data(url, callbackSuccess, callbackFailed);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_not_cancel_item_data(callbackSuccess, callbackFailed) {\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f6(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tevt_post_item_data(url, callbackSuccess, callbackFailed);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_modify_item_data(callbackSuccess, callbackFailed, eventId) {\n");
      out.write("\tvar url = '");
      if (_jspx_meth_s_005furl_005f7(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\tj$.post(url, {nursingId: eventId}, function(data){\n");
      out.write("\t\tif (data.nursingId > 0) {\n");
      out.write("\t\t\tvar url = '");
      if (_jspx_meth_s_005furl_005f8(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\twindow.location = iesAddToken(url + \"?id=\" + data.nursingId + \"&listType=3\");\n");
      out.write("\t\t}\n");
      out.write("\t}, \"json\")\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_post_item_data(url, callbackSuccess, callbackFailed) {\n");
      out.write("\tvar box = j$(\"#evt_editor_box\");\n");
      out.write("\tvar itemData = evt_make_item_data();\n");
      out.write("\n");
      out.write("\tbox.find(\"div.evt-message\").html(\"&nbsp;\");\n");
      out.write("\tj$.post(url, itemData, function(data){\n");
      out.write("\t\t\t\tvar oldId = box.find(\"[name=eventId]\").val();\n");
      out.write("\t\t\t\tif (data.result == \"success\") {\n");
      out.write("\t\t\t\t\tbox.dialog(\"close\");\n");
      out.write("\t\t\t\t\tif (callbackSuccess != undefined) {\n");
      out.write("\t\t\t\t\t\tcallbackSuccess(data.event, oldId);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tbox.find(\"div.evt-message\").html(data.message);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}, \"json\")\n");
      out.write("\t\t\t.done(function(){\n");
      out.write("\t\t\t})\n");
      out.write("\t\t\t.fail(function(){\n");
      out.write("\t\t\t\tif (callbackFailed != undefined) {\n");
      out.write("\t\t\t\t\tcallbackFailed(\"\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t})\n");
      out.write("\t\t\t.always(function(){\n");
      out.write("\t\t\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("function evt_make_item_data() {\n");
      out.write("\t/* eventId, type, copied, customerId, serviceYm,\n");
      out.write("\t   serviceCode, serviceDate, timeStart, timeEnd, \n");
      out.write("\t   helperId, followerId, travelTime, additionFirst, additionEmergency\n");
      out.write("\t */\n");
      out.write("\tvar result = new Object();\n");
      out.write("\tvar box = j$(\"#evt_editor_box\");\n");
      out.write("\t\n");
      out.write("\tbox.find(\".item-data\").each(function(){\n");
      out.write("\t\tif (j$(this).is(\"[type=checkbox]\")) {\n");
      out.write("\t\t\tif (j$(this).is(\":checked\")) {\n");
      out.write("\t\t\t\tresult[j$(this).attr(\"name\")] = 1;\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tresult[j$(this).attr(\"name\")] = 0;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tresult[j$(this).attr(\"name\")] = j$(this).val();\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\tresult.timeStart = result.timeStartHour + result.timeStartMinute;\n");
      out.write("\tresult.timeEnd = result.timeEndHour + result.timeEndMinute;\n");
      out.write("\t\n");
      out.write("\treturn result;\n");
      out.write("}");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent(null);
    // /scripts/event.js.jsp(6,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setAction("event-page");
    // /scripts/event.js.jsp(6,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setIncludeParams("none");
    // /scripts/event.js.jsp(6,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setNamespace("/js");
    int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
    if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f1 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f1.setParent(null);
    // /scripts/event.js.jsp(137,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setAction("event-page");
    // /scripts/event.js.jsp(137,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setIncludeParams("none");
    // /scripts/event.js.jsp(137,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setNamespace("/js");
    int _jspx_eval_s_005furl_005f1 = _jspx_th_s_005furl_005f1.doStartTag();
    if (_jspx_th_s_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f2 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f2.setParent(null);
    // /scripts/event.js.jsp(299,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f2.setAction("event!save");
    // /scripts/event.js.jsp(299,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f2.setIncludeParams("none");
    // /scripts/event.js.jsp(299,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f2.setNamespace("/js");
    int _jspx_eval_s_005furl_005f2 = _jspx_th_s_005furl_005f2.doStartTag();
    if (_jspx_th_s_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f3 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f3.setParent(null);
    // /scripts/event.js.jsp(304,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f3.setAction("event!copy");
    // /scripts/event.js.jsp(304,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f3.setIncludeParams("none");
    // /scripts/event.js.jsp(304,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f3.setNamespace("/js");
    int _jspx_eval_s_005furl_005f3 = _jspx_th_s_005furl_005f3.doStartTag();
    if (_jspx_th_s_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f4 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f4.setParent(null);
    // /scripts/event.js.jsp(309,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f4.setAction("event!delete");
    // /scripts/event.js.jsp(309,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f4.setIncludeParams("none");
    // /scripts/event.js.jsp(309,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f4.setNamespace("/js");
    int _jspx_eval_s_005furl_005f4 = _jspx_th_s_005furl_005f4.doStartTag();
    if (_jspx_th_s_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f5 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f5.setParent(null);
    // /scripts/event.js.jsp(314,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f5.setAction("event!cancel");
    // /scripts/event.js.jsp(314,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f5.setIncludeParams("none");
    // /scripts/event.js.jsp(314,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f5.setNamespace("/js");
    int _jspx_eval_s_005furl_005f5 = _jspx_th_s_005furl_005f5.doStartTag();
    if (_jspx_th_s_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f6 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f6.setParent(null);
    // /scripts/event.js.jsp(319,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f6.setAction("event!notCancel");
    // /scripts/event.js.jsp(319,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f6.setIncludeParams("none");
    // /scripts/event.js.jsp(319,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f6.setNamespace("/js");
    int _jspx_eval_s_005furl_005f6 = _jspx_th_s_005furl_005f6.doStartTag();
    if (_jspx_th_s_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f7 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f7.setParent(null);
    // /scripts/event.js.jsp(324,12) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f7.setAction("schedule!toNursingId");
    // /scripts/event.js.jsp(324,12) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f7.setIncludeParams("none");
    // /scripts/event.js.jsp(324,12) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f7.setNamespace("/js");
    int _jspx_eval_s_005furl_005f7 = _jspx_th_s_005furl_005f7.doStartTag();
    if (_jspx_th_s_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f7);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f8 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f8.setParent(null);
    // /scripts/event.js.jsp(327,14) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f8.setAction("nursing!edit");
    // /scripts/event.js.jsp(327,14) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f8.setIncludeParams("none");
    // /scripts/event.js.jsp(327,14) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f8.setNamespace("/");
    int _jspx_eval_s_005furl_005f8 = _jspx_th_s_005furl_005f8.doStartTag();
    if (_jspx_th_s_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f8);
    return false;
  }
}
